name: "🏗️ Build Plugin"

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v5
        id: dotnet
        with:
          dotnet-version: 8.0.x
      - name: Change default dotnet version
        run: |
          echo '{"sdk":{"version": "${{ steps.dotnet.outputs.dotnet-version }}"}}' > ./global.json
      - name: Install dependencies
        run: dotnet restore -p:UseLocalJellyfinReferences=true
      - name: Build
        run: dotnet build --no-restore -p:UseLocalJellyfinReferences=true
      - name: Test Stable lane
        run: dotnet test Jellyfin.Plugin.MetaShark.Test/Jellyfin.Plugin.MetaShark.Test.csproj --no-build --no-restore -p:UseLocalJellyfinReferences=true --filter "TestCategory=Stable" --logger "trx;LogFileName=metashark-stable.trx"
